#+TITLE: Oh My Laptop Ruby
#+OPTIONS: toc:nil num:nil ^:nil

This is part of [[https://github.com/xiaohanyu/oh-my-laptop][oh-my-laptop]].


* Packages

#+NAME: ruby-packages
#+CAPTION: ruby module packages
| Package            | Status   | Apt | Homebrew |
|--------------------+----------+-----+----------|
| [[https://github.com/sstephenson/rbenv][rbenv]]              | Required | OK  | OK       |
| [[https://github.com/sstephenson/ruby-build][ruby-build]]         | Required | OK  | OK       |
| [[https://github.com/sstephenson/rbenv-gem-rehash][rbenv-gem-rehash]]   | Required | OK  | OK       |
| [[https://github.com/sstephenson/rbenv-default-gems][rbenv-default-gems]] | Required | OK  | OK       |
| [[https://github.com/rbenv/rbenv-each][rbenv-each]]         | Required | OK  | OK       |
| [[https://github.com/rkh/rbenv-update][rbenv-update]]       | Required | OK  | OK       |
| [[http://bundler.io/][bundler]]            | Required | OK  | OK       |
| [[http://pryrepl.org/][pry]]                | Required | OK  | OK       |
| [[https://github.com/pry/pry-doc][pry-doc]]            | Required | OK  | OK       |


* rbenv

Ruby is an actively evolving language. Often you need to support multiple
versions of ruby with your code base. So you need tools to install, and switch
between multiple versions of ruby. [[http://rvm.io/][RVM]] is one of the most famous ruby version
manager tools, however, IMHO, it's just too bloated. I prefer [[https://github.com/sstephenson/rbenv][rbenv]] for now. Of
course there're other [[https://github.com/postmodern/chruby#alternatives][choices]], however, rbenv has various [[https://github.com/sstephenson/rbenv/wiki/Plugins][plugins]], which will
make your life much more easier.


* ruby-build

[[https://github.com/sstephenson/ruby-build][ruby-build]] is one of the most important plugins of rbenv, actually, you can
consider it as a sister project of rbenv. Just as its name, it helps to install
ruby. Please do read its [[https://github.com/sstephenson/ruby-build/wiki][wiki]] to ensure your have necessary packages installed
before you do your ruby-build.


* rbenv-gem-rehash

[[https://github.com/sstephenson/rbenv-gem-rehash][rbenv-gem-rehash]] automatically run =rbenv rehash= everytime you install or
uninstall a gem.


* rbenv-default-gems

[[https://github.com/sstephenson/rbenv-default-gems][rbenv-default-gems]] hooks into the =rbenv install= command to automatically
install gems listed in the =~/.rbenv/default-gems= file every time you install
a new version of Ruby.


** bundler

#+BEGIN_QUOTE
[[http://bundler.io/][Bundler]] provides a consistent environment for Ruby projects by tracking and
installing the exact gems and versions that are needed.

Bundler is an exit from dependency hell, and ensures that the gems you need are
present in development, staging, and production. Starting work on a project is
as simple as bundle install.

-- http://bundler.io/
#+END_QUOTE

oh-my-laptop provides two aliases for bundler:

#+BEGIN_SRC sh
alias b="bundle "
alias be="bundle exec "
#+END_SRC


** pry

[[http://pryrepl.org/][Pry]] is a powerful alternative to the standard IRB shell for Ruby. Just consider
it as [[http://ipython.org/][ipython]] in Ruby world.


** pry-doc

[[https://github.com/pry/pry-doc][pry-doc]] is a plugin for pry, which provides extended documentation support for
pry.

pry-doc extends two core pry commands: =show-doc= and =show-source= (aliased as
=?= and =$=, respectively). With the help of pry-doc, you can check the MRI C
code for ruby core statements, etc.


* rbenv-each

[[https://github.com/rbenv/rbenv-each][rbenv-each]] is a rbenv plugin which can run a command across all installed
rubies.


* rbenv-update

This [[https://github.com/sstephenson/rbenv][rbenv]] plugin adds the rbenv update command that updated rbenv and all
installed plugins.


* Reference

- [[http://kgrz.io/2014/02/13/Programmers-guide-to-choosing-ruby-version-manager.html][Programmer's guide to choosing a Ruby version manager]]
