#+TITLE: Oh My Laptop Ruby
#+OPTIONS: toc:nil num:nil ^:nil

This is part of [[https://github.com/xiaohanyu/oh-my-laptop][oh-my-laptop]].

* Packages

#+NAME: vcs-packages
#+CAPTION: vcs module packages
| Package    | Status   | Apt | Homebrew |
|------------+----------+-----+----------|
| [[https://github.com/sstephenson/rbenv][rbenv]]      | Required | OK  | OK       |
| [[https://github.com/sstephenson/ruby-build][ruby-build]] | Required | OK  | OK       |

* rbenv and ruby-build

Ruby is an actively evolving language. Often you need to support multiple
versions of ruby with your code base. So you need tools to install, and switch
between multiple versions of ruby. [[http://rvm.io/][RVM]] is one of the most famous ruby version
manager tools, however, IMHO, it's just too bloated. I prefer [[https://github.com/sstephenson/rbenv][rbenv]] for now. Of
course there're other [[https://github.com/postmodern/chruby#alternatives][choices]], however, rbenv has various [[https://github.com/sstephenson/rbenv/wiki/Plugins][plugins]], which will
make your life much more easier.

[[https://github.com/sstephenson/ruby-build][ruby-build]] is one of the most important plugins of rbenv, actually, you can
consider it as a sister project of rbenv. Just as its name, it helps to install
ruby. Please do read its [[https://github.com/sstephenson/ruby-build/wiki][wiki]] to ensure your have necessary packages installed
before you do your ruby-build.

* Reference

- [[http://kgrz.io/2014/02/13/Programmers-guide-to-choosing-ruby-version-manager.html][Programmer's guide to choosing a Ruby version manager]]
