#+TITLE: Oh My Laptop Basic
#+OPTIONS: toc:nil num:nil ^:nil

This is part of [[https://github.com/xiaohanyu/oh-my-laptop][oh-my-laptop]].

* Packages

#+NAME: basic-packages
#+CAPTION: basic module packages
| Package             | Status      | Apt | Homebrew |
|---------------------+-------------+-----+----------|
| [[https://github.com/ggreer/the_silver_searcher][the_silver_searcher]] | Required    | OK  | OK       |
| [[http://cloc.sourceforge.net/][cloc]]                | Required    | OK  | OK       |
| [[http://hisham.hm/htop/index.php][htop]]                | Required    | OK  | OK       |
| [[http://www.microbrew.org/tools/md5sha1sum/][md5sha1sum]]          | Required    | NaN | OK       |
| [[http://sourceforge.net/projects/proxychains-ng/][proxychains-ng]]      | Recommended | OK  | OK       |
| [[http://ranger.nongnu.org/][ranger]]              | Required    | OK  | OK       |
| [[https://github.com/hanslub42/rlwrap][rlwrap]]              | Required    | OK  | OK       |
| [[https://www.gnu.org/software/wget/][wget]]                | Required    | OK  | OK       |
| [[https://developer.apple.com/xcode/][tmux]]                | Required    | OK  | OK       |
| [[http://www.zsh.org/][zsh]]                 | Required    | OK  | OK       |
| [[https://github.com/robbyrussell/oh-my-zsh][oh-my-zsh]]           | Required    | OK  | OK       |
| [[http://editorconfig.org/][editorconfig]]        | Recommended | NaN | OK       |

* path_helper in OS X

When you install packages(such as mactex) via homebrew, you may see the
following text:

#+BEGIN_SRC sh
# $ brew cask install mactex
# ==> Caveats
# To use mactex, zsh users may need to add the following line to their
# ~/.zprofile.  (Among other effects, /usr/texbin will be added to the
# PATH environment variable):

#   eval `/usr/libexec/path_helper -s`
if [[ -f /usr/libexec/path_helper ]]; then
    eval `/usr/libexec/path_helper -s`
fi
#+END_SRC

Seems strange, ha? [[https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/path_helper.8.html][path_helper]] is a binary executable which helps you to
construct proper ~$PATH~ variable through ~/etc/paths/~ and files in
~/etc/path.d/~. However, when ~/usr/libexec/path_helper -s~, it depends on the
current ~$PATH~ variable, which is not sure in different moment, that's all
trouble begins. I prefer to provide an empty ~PATH=""~ variable when
~/usr/libexec/path_helper -s~. So I replace ~/etc/profile~ and ~/etc/zshenv~
when oh-my-laptop runs, so I can get more precise control over ~$PATH~.

Refs:

- [[http://www.softec.lu/site/DevelopersCorner/MasteringThePathHelper][Mastering the path_helper utility of Mac OS X]]
- [[http://unix.stackexchange.com/questions/22979/path-helper-and-zsh][path_helper and zsh]]
- [[http://stackoverflow.com/questions/12409270/os-x-mountain-lion-how-does-path-helper-work][OS X Mountain Lion: how does path_helper work?]]

* the_silver_searcher

#+BEGIN_QUOTE
A lot of my time spent “writing” code is actually spent reading code. And a
decent chunk of my time spent reading code is actually spent searching
code. Lately I’ve started working with a larger codebase. Both grep and ack
take a non-negligible amount of time to search it. Both are slow, but for
different reasons. Grep is fast, but doesn’t ignore files. Ack is very good
at ignoring files, but it’s written in Perl instead of C. What I really want is
something that’s fast and ignores files.

-- [[http://geoff.greer.fm/2011/12/27/the-silver-searcher-better-than-ack/][The Silver Searcher: Better than Ack]]
#+END_QUOTE

You can not go back to [[http://beyondgrep.com][ack]] after the first you try ag. There're lots of
third-party ag integration for various editors, check [[http://betterthanack.com/][betterthanack]].

* cloc

[[http://cloc.sourceforge.net/][cloc]] is a line-of-code counter tool to get an overview and generate a loc
report for your project. It's simple, portable, and it just works as expected.

* htop

[[http://hisham.hm/htop/index.php][htop]] is an interactive process viewer for Linux(and ported to Mac OS X). It is
a text-mode application and requires [[http://en.wikipedia.org/wiki/Ncurses][ncurses]] library.

It's a better replacement for the traditional builtin [[http://en.wikipedia.org/wiki/Top_(software)][top]] program.

Type =h= from within =htop= to get instant help.

* md5sha1sum

[[http://www.microbrew.org/tools/md5sha1sum/][md5sha1sum]] package provides the missing =md5sum=, =sha1sum= command for Mac OS
X.

* proxychains-ng

[[http://sourceforge.net/projects/proxychains-ng/][proxychains]] is a proxifier dedicated for Linux and other Unix system, it allows
TCP and DNS tunneling through proxies and it support HTTP, SOCKS4 and SOCKS5
proxy servers. Different proxy types can be mixed in the same chain.

If you live in china, then you know why you need a proxy. If you're a CLI guru,
then proxychains is a pratically excellent proxy solution for most of your CLI
programs.

Generally, you need an existing proxy(Socks or HTTP). Then prefix
=proxychais-ng= to any command you want to execute, then your command should
get data from Internet via your proxy.

* ranger

[[http://ranger.nongnu.org/][ranger]] is a CLI file manager with VI key bindings. Just as htop, ranger depends
[[http://en.wikipedia.org/wiki/Ncurses][ncurses]] library. It provides a minimalistic and nice CLI interface with VI key
bindings for fast file and directory navigation. It can also guess which
program you want to use when open particular files.

Try it and I'm sure you will fall in love with it. Check its [[http://ranger.nongnu.org/screenshots.html][screenshots]] for
some intuition.

* rlwrap

[[https://github.com/hanslub42/rlwrap][rlwrap]] is a 'readline wrapper', a small utility that uses the GNU readline
library to allow the editing of keyboard input for any command. You have
rlwrap, then you have the great, pervasive readline's history, search,
shortcuts at your fingertips for any CLI programs.

Here's some tutorials from its home page:

** HOW TO USE IT:

If

#+BEGIN_SRC
$ <command> <args>
#+END_SRC

doesn't let you use arrow keys to edit input, or if you just want decent input
history and completion, try:

#+BEGIN_SRC
$ rlwrap [-options] <command> <args>
#+END_SRC

You then can edit =<command>='s input and recall the input history using the
arrow keys.  Input history is remembered accross invocations, separately for
different =<command>=. Typing =!<prefix><TAB>= will recall the last input line
starting with =<prefix>=, =CTRL-R= will search the input history.  With the
=-r= and =-f= options you can specify the list of words which rlwrap will use
as possible completions, taking them from a file (=-f= option) or from
=<command>='s standard in/output.  rlwrap monitors =<command>='s terminal settings,
so that it can do the right thing when command asks for single keypresses or
for a password.  Commands that already use readline will always ask for (and
get) single keypresses, which makes rlwrapping them rather pointless. However,
if one uses the =-a= option, rlwrap will use its own line editing and
history. Unforunately, in this case, rlwrap cannot detect whether =<command>=
asks for a password. This can be remedied by giving the password prompt
(excluding trailing space and possibly the first few letters) as an argument to
the =-a= option.

** EXAMPLES:
Run netcat with command-line editing:

#+BEGIN_SRC
rlwrap nc localhost 80
#+END_SRC

Run lprolog and use library1 and library2 to build a completion word
list:

#+BEGIN_SRC
rlwrap -f library1 -f library2 lprolog
#+END_SRC

Run smbclient (which already uses readline), add all input and output
to completion list, complete local filenames, avoid showing (and
storing) passwords:

#+BEGIN_SRC
rlwrap -cr -aPassword: smbclient '\\PEANUT\C'
#+END_SRC
* texinfo

Besides [[http://en.wikipedia.org/wiki/Man_page][man pages]], GNU [[http://www.gnu.org/software/texinfo/][texinfo]] is another popular documentation system, and it
is the official documentation format for the GNU project.

Some packages may need texinfo to faciliate the build process. So we add it
here.

* wget

GNU Wget is a free software package for retrieving files using HTTP, HTTPS and
FTP, the most widely-used Internet protocols.

Mac OS X didn't has it by default, so we add it here.
* tmux

tmux is a terminal multiplexer.

By multiplexer, it means you can create windows, panels in a single terminal
windows. No need for traditional vertical or horizontal splitting features from
terminal emulators. You can switch between windows, panels without touching the
mouse, and you can create, attach, detach sessions at any time. IMHO, tmux is a
killer app for CLI gurus.

There's a wonderful book, <[[https://pragprog.com/book/bhtmux/tmux][tmux: Productive Mouse-Free Development]]> by [[http://bphogan.com/][Brian
P.Hogan]]. oh-my-laptop steals some code snippets from this book and replace the
prefix key =C-b= with =C-l=. Note that tmux's key bindings is case sensitive,
so when weird things happened, check your CAPSLOCK first.

Last but now least, you'd better install latest version tmux to avoid some
weird bugs. On ubuntu, you can do like [[http://stackoverflow.com/questions/25940944/ugrade-tmux-from-1-8-to-1-9-on-ubuntu-14-04][this]].

* zsh and oh-my-zsh

[[http://www.zsh.org/][zsh]] is a shell designed for interactive use. Many of the useful features of
bash, ksh, and tcsh were incorporated into zsh; many original features were
added. Check the following posts to get some knowledge about why zsh is a much
more cooler option than bash:

- [[http://code.joejag.com/2014/why-zsh.html][My favourite Zsh features]]
- [[http://mikebuss.com/2014/02/02/a-beautiful-productive-terminal-experience/][A Beautifully Productive Terminal Experience]]
- [[http://mikegrouchy.com/blog/2012/01/zsh-is-your-friend.html][Zsh is your friend]]

[[http://ohmyz.sh][oh-my-zsh]] is a community-driven framework for managing your zsh
configuration. Includes 180+ optional [[https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins][plugins]] (rails, git, OS X, hub,
capistrano, brew, ant, php, python, etc), over 120 [[https://github.com/robbyrussell/oh-my-zsh/wiki/Themes][themes]] to spice up your
morning, and an auto-update tool so that makes it easy to keep up with the
latest updates from the community.

* editorconfig

We live in a world with multiple editors or IDEs, and often we need
collaboration with others. [[http://editorconfig.org/][EditorConfig]] helps developers define and maintain
consistent coding styles between different editors and IDEs. The EditorConfig
project consists of a file format for defining coding styles and a collection
of text editor plugins that enable editors to read the file format and adhere
to defined styles. EditorConfig files are easily readable and they work nicely
with version control systems.

Check [[https://github.com/editorconfig/editorconfig-core-c/blob/master/INSTALL.md][github]] for detailed installation instructions.
