---

- name: install mactex
  homebrew_cask:
    name:
      - mactex
    state: present

- name: install pandoc
  homebrew:
    name:
      - pandoc
    state: present

- set_fact:
    role_tex_done: true
