#+TITLE: Oh My Laptop Java
#+OPTIONS: toc:nil num:nil ^:nil

This is part of [[https://github.com/xiaohanyu/oh-my-laptop][oh-my-laptop]].


* Packages

- [[http://www.oracle.com/technetwork/java/javase/overview/java8-2100321.html][Java 8]]
- [[http://maven.apache.org/][maven]]
- [[https://gradle.org/][gradle]]


* Java

** Mac OS X

The vanilla OS X contains a fake =java= command which will lead you to Oracle's
[[https://www.java.com/en/download/][site]]. Then you download a package, you click on it, you get Java
installed. Fortunately, we have [[https://github.com/caskroom/homebrew-cask][homebrew-cask]], and we can get Java by =brew
cask install java=. And ansible has builtin [[http://docs.ansible.com/homebrew_cask_module.html][module]] support for homebrwe-cask.


** Ubuntu

It is a little complicated to install Java via CLI on Ubuntu, generally, you
need to:

1. add a java [[https://launchpad.net/~webupd8team/+archive/ubuntu/java][ppa]] for apt
2. add some *WEIRD* keys
3. accept Oracle's license
4. finally you can =sudo apt-get install=

Most of us have little time to touch the internals of =apt-get=, so I just
figure out an ansible playbook and it works, that's enough.


* Maven

[[http://maven.apache.org/][Maven]] is the defacto build tool in Java world. It's easy to install it.


* Gradle

[[http://gradle.org/][Gradle]] is rising build tool in Java world, it is based on [[http://groovy.codehaus.org/][Groovy]], so the syntax
of gradle is much more simpler than maven's old-fashioned XML.
