---

- name: git clone|pull pyenv repo
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{user_home}}/.pyenv"
    update: yes

- name: install multiple plugins for pyenv
  git:
    repo: "https://github.com/pyenv/{{item}}.git"
    dest: "{{user_home}}/.pyenv/plugins/{{item}}"
    update: yes
  with_items:
    - pyenv-doctor
    - pyenv-pip-rehash
    - pyenv-update
    - pyenv-virtualenv
    - pyenv-which-ext

- name: set-up pyenv init file
  become: false
  copy: src=pyenv-init.sh dest={{user_home}}/.oh-my-laptop/pyenv-init.sh

- set_fact:
    role_python_done: true
