---

- name: install some small, awesome packages to boost your life
  homebrew: name={{item}} state=present
  with_items:
    - ag
    - cloc
    - htop-osx
    - md5sha1sum
    - proxychains-ng
    - ranger
    - rlwrap
    - texinfo
    - wget
    - tig
    - tmux
    - editorconfig
    - reattach-to-user-namespace
    - ssh-copy-id
    # - cscope
    # - nmon   # not found in homebrew
    # - pinfo  # not found in homebrew

# zsh and oh-my-zsh
- name: install zsh
  homebrew: name={{item}} state=present
  with_items:
    - zsh
    - zsh-lovers

- name: replace /etc/profile
  copy: src=profile.etc dest=/etc/profile
  sudo: yes

- name: replace /etc/zshenv
  copy: src=zshenv.etc dest=/etc/zshenv
  sudo: yes
