---

# install some fancy tools
- name: install some small, awesome packages to boost your life
  become: false
  homebrew:
    name:
      - ag
      - autojump
      - editorconfig
      - global
      - htop-osx
      - httpie
      - jq
      - md5sha1sum
      - pstree
      - ranger
      - rlwrap
      - texinfo
      - tokei
      - tig
      - tldr
      - tmux
      - wget
    state: present

# add a tmux.conf
- name: settings tmux.conf
  copy: src=tmux.conf dest={{user_home}}/.tmux.conf

- name: set-up autojump init file
  copy: src=autojump-init.sh dest={{user_home}}/.autojump-init.sh

- set_fact:
    role_basic_done: true
