---

- name: install docker via homebrew cask
  homebrew_cask:
    name: docker
    state: present

- name: set-up docker init file
  copy: src=docker-init.sh dest={{user_home}}/.oh-my-laptop/docker-init.sh

- set_fact:
    role_docker_done: true
